name: Build executable
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - run: pip install -r requirements.txt pyinstaller
    - run: python pyi_run.py

    - uses: actions/upload-artifact@v2
    with:
      path: dist/*