name: Build executable
on:
  push:
    tags:
      - '*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'windows-2022']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build installer
      run: python pyi_run.py

    - name: Apply post-processing (MacOS)
      if: matrix.os == 'macos-11'
      run: |
        cd dist
        tar -cvf annotator.tar annotator
        rm -rf annotator annotator.app
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: annotator_${{matrix.os}}
        path: dist/*

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: annotator_${{matrix.os}}

    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: annotator_${{matrix.os}}.zip
        asset_name: annotator_${{matrix.os}}.zip
        asset_content_type: application/zip