name: Build executable
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11']

    steps:
    - name: Checkout cde
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build installer
      run: python pyi_run.py

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: annotator_${{matrix.os}}
        path: dist/*